### ISSUE TITLE
Alguns erros encontrados no estudo de caso do Zookeeper e Talvez sistemas de arquivos

### ISSUE THREAD

**Issue by samuel-cavalcanti** [lasarojc/ds_notes#14]
Olá professor boa noite. Eu estava revisitando um dos seus materiais mais especificamente o sistemas de arquivos distribuídos. 
Professor eu encontrei o link para receitas do Zooker quebrado, sendo o atual seria esse: https://zookeeper.apache.org/doc/r3.4.14/recipes.html  (agora eles colocam a versão na url)

 
![image](https://user-images.githubusercontent.com/24573157/169441562-804acdda-3694-4866-af90-ac3dbaf2a9da.png)
também notei um  __\emph{leases}__, um possível erro ao passar do lex para markdown.

**Comment by lasarojc** [comment]
obrigado, Samuel.
eles mudaram o nome do branch principal de trunk para current. já atualizei.

no mais, como está a vida? graduou-se?
Lásaro

**Comment by samuel-cavalcanti** [comment]
Na vida, estou na luta igual a todo mundo. Na graduação está como na vida.
Falta 1 matéria, 1 estágio, 1 Tcc.
Vai dar certo.

Em sex., 20 de mai. de 2022 às 12:47, Lasaro Camargos <
***@***.***> escreveu:
