### ISSUE TITLE
Link leitura socket quebrado (ainda é possível acessar o conteúdo)

### ISSUE THREAD

**Issue by gustavo-candido** [lasarojc/ds_notes#2]
URL: https://lasarojc.github.io/teaching/gbc074gsi028/semana1/
OBS: ainda é possível acessar via https://lasarojc.github.io/ds_notes/basics/#no-principio-era-o-socket
![Peek 2020-11-03 04-30](https://user-images.githubusercontent.com/39497287/97959147-75ddda80-1d8d-11eb-8b28-1dea0d006f56.gif)

**Comment by lasarohedvig** [comment]
obrigado por apontar.
corrigido!
