### ISSUE TITLE
Dúvidas sobre a recomedação do OpenReplica e talvez um link não atualizado

### ISSUE THREAD

**Issue by samuel-cavalcanti** [lasarojc/ds_notes#4]
Professor porque [OpenReplica](https://github.com/denizalti/openreplica) é uma boa recomendação ?  
Faz muito tempo que não tem nenhuma atualização

![image](https://user-images.githubusercontent.com/24573157/136064002-d99ded5b-06fd-4194-b7c0-e09e25bf4bef.png)
https://lasarojc.github.io/ds_notes/projeto/#etapa-2-banco-de-dados-replicado

talvez o link do Ratis seja esse :
https://lasarojc.github.io/ds_notes/cases/ratis/

**Comment by lasarojc** [comment]
O open replica funcionava bem, e parecia bem simples de colocar para rodar.
Vários alunos o usaram com sucesso. Mas se está parado, realmente pode ser
um problema.  De uma olhada no Jira do projeto e veja se tem muitas issues
abertas.

Vou corrigir o link. Obrigado por apontar o problema.
